name: CD

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PUSH_TOKEN }}
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.SSH_USERNAME }}
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: 'cd /usr/share/nginx/html/m-integrated-test && sudo chmod +x server_deploy.sh && ./server_deploy.sh'
